language: c

env:
  global:
    # coverity token
    - secure: "dx0HqrtHdpgkV+v3jQiWuCPKZIc1pEBmMyhfhq5ah6+1AK/gzop5vVHzzBdLezGnsloutDN4Q/jiCWZORn3ZexxwFMnHCPQwkzkqo8s8UnAW4pXaAzqR/9tyYoyjpXXxjKBobS6aiLiWx7WFx9msO6a3arq/El8k21AnC05Dr2c="
  matrix:
    # standard builds
    - CC=gcc
    - CC=clang
    # cross-compile using mingw
    - CC= PLATFORM="mingw32" ARCH="x86"
    - CC= PLATFORM="mingw32" ARCH="x86_64"

script: ./travis-ci-build.sh

before_install:
  - echo "yes" | sudo apt-add-repository ppa:zoogie/sdl2-snapshots
  - sudo apt-get update -qq
  - sudo apt-get remove -qq -y mingw32
  - sudo apt-get install -q -y libgl1-mesa-dev libsdl2-dev mingw-w64

notifications:
  irc: "irc.freenode.org#spearmint"
  on_success: change
  on_failure: always

addons:
  coverity_scan:
    project:
      name: "zturtleman/spearmint"
      description: "Build submitted via Travis CI"
    notification_email: zturtleman@gmail.com
    build_command_prepend: "make clean"
    build_command: "make release"
    branch_pattern: master
